//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace MHM.WinFlexOne.Services.Integration.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ServiceRegistryConfig {
        
        private ServiceInstanceInfo[] serviceInstancesField;
        
        private ServiceDefinition[] serviceDefinitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ServiceInstance", IsNullable=false)]
        public ServiceInstanceInfo[] ServiceInstances {
            get {
                return this.serviceInstancesField;
            }
            set {
                this.serviceInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceDefinition[] ServiceDefinitions {
            get {
                return this.serviceDefinitionsField;
            }
            set {
                this.serviceDefinitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WcfServiceInstanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectServiceInstanceInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class ServiceInstanceInfo {
        
        private string idField;
        
        private string serviceDefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string ServiceDefinition {
            get {
                return this.serviceDefinitionField;
            }
            set {
                this.serviceDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceDefinition {
        
        private string interfaceTypeField;
        
        private ServiceCreationEnum serviceCreationModelField;
        
        private string defaultInstanceField;
        
        private string addressField;
        
        private BindingEnum bindingField;
        
        private string idField;
        
        /// <remarks/>
        public string InterfaceType {
            get {
                return this.interfaceTypeField;
            }
            set {
                this.interfaceTypeField = value;
            }
        }
        
        /// <remarks/>
        public ServiceCreationEnum ServiceCreationModel {
            get {
                return this.serviceCreationModelField;
            }
            set {
                this.serviceCreationModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="IDREF")]
        public string DefaultInstance {
            get {
                return this.defaultInstanceField;
            }
            set {
                this.defaultInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public BindingEnum Binding {
            get {
                return this.bindingField;
            }
            set {
                this.bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum ServiceCreationEnum {
        
        /// <remarks/>
        Singleton,
        
        /// <remarks/>
        PerCall,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum BindingEnum {
        
        /// <remarks/>
        NetTcp,
        
        /// <remarks/>
        HTTP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WcfServiceInstanceInfo : ServiceInstanceInfo {
        
        private string uriField;
        
        private string endPointNameField;
        
        private string dataContractSerializerBehaviourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        public string EndPointName {
            get {
                return this.endPointNameField;
            }
            set {
                this.endPointNameField = value;
            }
        }
        
        /// <remarks/>
        public string DataContractSerializerBehaviour {
            get {
                return this.dataContractSerializerBehaviourField;
            }
            set {
                this.dataContractSerializerBehaviourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObjectServiceInstanceInfo : ServiceInstanceInfo {
        
        private string serviceClassNameField;
        
        /// <remarks/>
        public string ServiceClassName {
            get {
                return this.serviceClassNameField;
            }
            set {
                this.serviceClassNameField = value;
            }
        }
    }
}
