//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace MHM.WinFlexOne.Services.Integration.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ServiceBrokerConfig {
        
        private ContainerInfo containerField;
        
        private FactoryConfiguration factoryConfigField;
        
        /// <remarks/>
        public ContainerInfo Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        /// <remarks/>
        public FactoryConfiguration FactoryConfig {
            get {
                return this.factoryConfigField;
            }
            set {
                this.factoryConfigField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContainerInfo {
        
        private string typeField;
        
        private string idField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FactoryInfo {
        
        private string typeField;
        
        private string idField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FactoryReference {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FactoryOverrideConfig {
        
        private FactoryReference factoryField;
        
        private string serviceInterfaceField;
        
        /// <remarks/>
        public FactoryReference Factory {
            get {
                return this.factoryField;
            }
            set {
                this.factoryField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceInterface {
            get {
                return this.serviceInterfaceField;
            }
            set {
                this.serviceInterfaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FactoryConfiguration {
        
        private FactoryOverrideConfig[] factoryOverridesField;
        
        private FactoryInfo[] factoriesField;
        
        private FactoryReference defaultFactoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Override", IsNullable=false)]
        public FactoryOverrideConfig[] FactoryOverrides {
            get {
                return this.factoryOverridesField;
            }
            set {
                this.factoryOverridesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Factory", IsNullable=false)]
        public FactoryInfo[] Factories {
            get {
                return this.factoriesField;
            }
            set {
                this.factoriesField = value;
            }
        }
        
        /// <remarks/>
        public FactoryReference DefaultFactory {
            get {
                return this.defaultFactoryField;
            }
            set {
                this.defaultFactoryField = value;
            }
        }
    }
}
